### ISSUE TITLE
Gating mechanism

### ISSUE THREAD

**Issue by vgaraujov** [ivanmontero/autobot#2]
Hello @ivanmontero, interesting work what you did. I was trying to find where part of the code is the gating method you mentioned in section 2.2 (Decoder) of the paper. Could you tell me what script it is in? 

Thank you in advance!

**Comment by ivanmontero** [comment]
Hey @vgaraujov, thanks for your interest! The gating method can be found where the autoencoder layers are defined: https://github.com/ivanmontero/autobot/blob/master/fairseq/fairseq/modules/autoencoder_layer.py#L209

Apologies for the late reply (PhD Applications have been hectic!)
